/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as SaveRouteImport } from './routes/save'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OutfitsRouteImport } from './routes/outfits'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MorningRouteImport } from './routes/morning'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LentRouteImport } from './routes/lent'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as BeforeYouBuyRouteImport } from './routes/before-you-buy'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FoldersIndexRouteImport } from './routes/folders.index'
import { Route as ShareDepartingRouteImport } from './routes/share.departing'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ItemItemIdRouteImport } from './routes/item.$itemId'
import { Route as FoldersFolderIdRouteImport } from './routes/folders.$folderId'
import { Route as ApiColorAnalysisRouteImport } from './routes/api/color-analysis'
import { Route as ShareFolderFolderIdRouteImport } from './routes/share.folder.$folderId'

const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const SaveRoute = SaveRouteImport.update({
  id: '/save',
  path: '/save',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OutfitsRoute = OutfitsRouteImport.update({
  id: '/outfits',
  path: '/outfits',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningRoute = MorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LentRoute = LentRouteImport.update({
  id: '/lent',
  path: '/lent',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const BeforeYouBuyRoute = BeforeYouBuyRouteImport.update({
  id: '/before-you-buy',
  path: '/before-you-buy',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersIndexRoute = FoldersIndexRouteImport.update({
  id: '/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareDepartingRoute = ShareDepartingRouteImport.update({
  id: '/share/departing',
  path: '/share/departing',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ItemItemIdRoute = ItemItemIdRouteImport.update({
  id: '/item/$itemId',
  path: '/item/$itemId',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersFolderIdRoute = FoldersFolderIdRouteImport.update({
  id: '/folders/$folderId',
  path: '/folders/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiColorAnalysisRoute = ApiColorAnalysisRouteImport.update({
  id: '/api/color-analysis',
  path: '/api/color-analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareFolderFolderIdRoute = ShareFolderFolderIdRouteImport.update({
  id: '/share/folder/$folderId',
  path: '/share/folder/$folderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/before-you-buy': typeof BeforeYouBuyRoute
  '/inbox': typeof InboxRoute
  '/lent': typeof LentRoute
  '/login': typeof LoginRoute
  '/morning': typeof MorningRoute
  '/onboarding': typeof OnboardingRoute
  '/outfits': typeof OutfitsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/save': typeof SaveRoute
  '/trends': typeof TrendsRoute
  '/tutorial': typeof TutorialRoute
  '/wishlist': typeof WishlistRoute
  '/api/color-analysis': typeof ApiColorAnalysisRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/share/departing': typeof ShareDepartingRoute
  '/folders/': typeof FoldersIndexRoute
  '/share/folder/$folderId': typeof ShareFolderFolderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/before-you-buy': typeof BeforeYouBuyRoute
  '/inbox': typeof InboxRoute
  '/lent': typeof LentRoute
  '/login': typeof LoginRoute
  '/morning': typeof MorningRoute
  '/onboarding': typeof OnboardingRoute
  '/outfits': typeof OutfitsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/save': typeof SaveRoute
  '/trends': typeof TrendsRoute
  '/tutorial': typeof TutorialRoute
  '/wishlist': typeof WishlistRoute
  '/api/color-analysis': typeof ApiColorAnalysisRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/share/departing': typeof ShareDepartingRoute
  '/folders': typeof FoldersIndexRoute
  '/share/folder/$folderId': typeof ShareFolderFolderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/before-you-buy': typeof BeforeYouBuyRoute
  '/inbox': typeof InboxRoute
  '/lent': typeof LentRoute
  '/login': typeof LoginRoute
  '/morning': typeof MorningRoute
  '/onboarding': typeof OnboardingRoute
  '/outfits': typeof OutfitsRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/save': typeof SaveRoute
  '/trends': typeof TrendsRoute
  '/tutorial': typeof TutorialRoute
  '/wishlist': typeof WishlistRoute
  '/api/color-analysis': typeof ApiColorAnalysisRoute
  '/folders/$folderId': typeof FoldersFolderIdRoute
  '/item/$itemId': typeof ItemItemIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/share/departing': typeof ShareDepartingRoute
  '/folders/': typeof FoldersIndexRoute
  '/share/folder/$folderId': typeof ShareFolderFolderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/before-you-buy'
    | '/inbox'
    | '/lent'
    | '/login'
    | '/morning'
    | '/onboarding'
    | '/outfits'
    | '/profile'
    | '/reset-password'
    | '/save'
    | '/trends'
    | '/tutorial'
    | '/wishlist'
    | '/api/color-analysis'
    | '/folders/$folderId'
    | '/item/$itemId'
    | '/share/$shareId'
    | '/share/departing'
    | '/folders/'
    | '/share/folder/$folderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/before-you-buy'
    | '/inbox'
    | '/lent'
    | '/login'
    | '/morning'
    | '/onboarding'
    | '/outfits'
    | '/profile'
    | '/reset-password'
    | '/save'
    | '/trends'
    | '/tutorial'
    | '/wishlist'
    | '/api/color-analysis'
    | '/folders/$folderId'
    | '/item/$itemId'
    | '/share/$shareId'
    | '/share/departing'
    | '/folders'
    | '/share/folder/$folderId'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/before-you-buy'
    | '/inbox'
    | '/lent'
    | '/login'
    | '/morning'
    | '/onboarding'
    | '/outfits'
    | '/profile'
    | '/reset-password'
    | '/save'
    | '/trends'
    | '/tutorial'
    | '/wishlist'
    | '/api/color-analysis'
    | '/folders/$folderId'
    | '/item/$itemId'
    | '/share/$shareId'
    | '/share/departing'
    | '/folders/'
    | '/share/folder/$folderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  BeforeYouBuyRoute: typeof BeforeYouBuyRoute
  InboxRoute: typeof InboxRoute
  LentRoute: typeof LentRoute
  LoginRoute: typeof LoginRoute
  MorningRoute: typeof MorningRoute
  OnboardingRoute: typeof OnboardingRoute
  OutfitsRoute: typeof OutfitsRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SaveRoute: typeof SaveRoute
  TrendsRoute: typeof TrendsRoute
  TutorialRoute: typeof TutorialRoute
  WishlistRoute: typeof WishlistRoute
  ApiColorAnalysisRoute: typeof ApiColorAnalysisRoute
  FoldersFolderIdRoute: typeof FoldersFolderIdRoute
  ItemItemIdRoute: typeof ItemItemIdRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
  ShareDepartingRoute: typeof ShareDepartingRoute
  FoldersIndexRoute: typeof FoldersIndexRoute
  ShareFolderFolderIdRoute: typeof ShareFolderFolderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/save': {
      id: '/save'
      path: '/save'
      fullPath: '/save'
      preLoaderRoute: typeof SaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/outfits': {
      id: '/outfits'
      path: '/outfits'
      fullPath: '/outfits'
      preLoaderRoute: typeof OutfitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning': {
      id: '/morning'
      path: '/morning'
      fullPath: '/morning'
      preLoaderRoute: typeof MorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lent': {
      id: '/lent'
      path: '/lent'
      fullPath: '/lent'
      preLoaderRoute: typeof LentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/before-you-buy': {
      id: '/before-you-buy'
      path: '/before-you-buy'
      fullPath: '/before-you-buy'
      preLoaderRoute: typeof BeforeYouBuyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/': {
      id: '/folders/'
      path: '/folders'
      fullPath: '/folders/'
      preLoaderRoute: typeof FoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/departing': {
      id: '/share/departing'
      path: '/share/departing'
      fullPath: '/share/departing'
      preLoaderRoute: typeof ShareDepartingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/item/$itemId': {
      id: '/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/item/$itemId'
      preLoaderRoute: typeof ItemItemIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders/$folderId': {
      id: '/folders/$folderId'
      path: '/folders/$folderId'
      fullPath: '/folders/$folderId'
      preLoaderRoute: typeof FoldersFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/color-analysis': {
      id: '/api/color-analysis'
      path: '/api/color-analysis'
      fullPath: '/api/color-analysis'
      preLoaderRoute: typeof ApiColorAnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/folder/$folderId': {
      id: '/share/folder/$folderId'
      path: '/share/folder/$folderId'
      fullPath: '/share/folder/$folderId'
      preLoaderRoute: typeof ShareFolderFolderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  BeforeYouBuyRoute: BeforeYouBuyRoute,
  InboxRoute: InboxRoute,
  LentRoute: LentRoute,
  LoginRoute: LoginRoute,
  MorningRoute: MorningRoute,
  OnboardingRoute: OnboardingRoute,
  OutfitsRoute: OutfitsRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SaveRoute: SaveRoute,
  TrendsRoute: TrendsRoute,
  TutorialRoute: TutorialRoute,
  WishlistRoute: WishlistRoute,
  ApiColorAnalysisRoute: ApiColorAnalysisRoute,
  FoldersFolderIdRoute: FoldersFolderIdRoute,
  ItemItemIdRoute: ItemItemIdRoute,
  ShareShareIdRoute: ShareShareIdRoute,
  ShareDepartingRoute: ShareDepartingRoute,
  FoldersIndexRoute: FoldersIndexRoute,
  ShareFolderFolderIdRoute: ShareFolderFolderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
