-- Clem: brand reference table
-- Seeds ~1000 real apparel/fashion brand names, grouped by category.
-- Intended use: constrain/ground AI image-classification output (e.g. a
-- vision model picking a plausible brand for a scanned clothing item)
-- against a known list instead of hallucinating a name.
--
-- Run this in the Supabase dashboard: SQL Editor -> New query -> paste -> Run.

create table if not exists public.brands (
  id bigint generated always as identity primary key,
  name text not null unique,
  category text not null,
  created_at timestamptz not null default now()
);

comment on table public.brands is 'Reference list of apparel/fashion brand names used to ground AI image classification.';
comment on column public.brands.category is 'Rough grouping, e.g. luxury, contemporary, fast_fashion, denim, activewear, footwear, streetwear, accessories, etc.';

create index if not exists brands_category_idx on public.brands (category);
create index if not exists brands_name_lower_idx on public.brands (lower(name));

-- Row Level Security: this is a shared reference table, not user data.
-- Anyone (including anon) can read it; only the service role can write.
alter table public.brands enable row level security;

drop policy if exists "Brands are publicly readable" on public.brands;
create policy "Brands are publicly readable"
  on public.brands for select
  to anon, authenticated
  using (true);

-- Seed data (on conflict do nothing so this script is safe to re-run).
insert into public.brands (name, category)
values
  ('Chanel', 'luxury'),
  ('Louis Vuitton', 'luxury'),
  ('Gucci', 'luxury'),
  ('Prada', 'luxury'),
  ('Dior', 'luxury'),
  ('Hermès', 'luxury'),
  ('Fendi', 'luxury'),
  ('Balenciaga', 'luxury'),
  ('Saint Laurent', 'luxury'),
  ('Givenchy', 'luxury'),
  ('Valentino', 'luxury'),
  ('Versace', 'luxury'),
  ('Bottega Veneta', 'luxury'),
  ('Celine', 'luxury'),
  ('Loewe', 'luxury'),
  ('Burberry', 'luxury'),
  ('Alexander McQueen', 'luxury'),
  ('Miu Miu', 'luxury'),
  ('Dolce & Gabbana', 'luxury'),
  ('Armani', 'luxury'),
  ('Giorgio Armani', 'luxury'),
  ('Emporio Armani', 'luxury'),
  ('Ralph Lauren', 'luxury'),
  ('Tom Ford', 'luxury'),
  ('Chloé', 'luxury'),
  ('Stella McCartney', 'luxury'),
  ('Off-White', 'luxury'),
  ('Moncler', 'luxury'),
  ('Brunello Cucinelli', 'luxury'),
  ('Loro Piana', 'luxury'),
  ('Ermenegildo Zegna', 'luxury'),
  ('Salvatore Ferragamo', 'luxury'),
  ('Jimmy Choo', 'luxury'),
  ('Christian Louboutin', 'luxury'),
  ('Manolo Blahnik', 'luxury'),
  ('Roger Vivier', 'luxury'),
  ('Balmain', 'luxury'),
  ('Lanvin', 'luxury'),
  ('Marni', 'luxury'),
  ('Jil Sander', 'luxury'),
  ('Alaïa', 'luxury'),
  ('Thom Browne', 'luxury'),
  ('Rick Owens', 'luxury'),
  ('Comme des Garçons', 'luxury'),
  ('Yohji Yamamoto', 'luxury'),
  ('Issey Miyake', 'luxury'),
  ('Maison Margiela', 'luxury'),
  ('Acne Studios', 'luxury'),
  ('Vetements', 'luxury'),
  ('Isabel Marant', 'luxury'),
  ('Proenza Schouler', 'luxury'),
  ('The Row', 'luxury'),
  ('Khaite', 'luxury'),
  ('Toteme', 'luxury'),
  ('Jacquemus', 'luxury'),
  ('Bode', 'luxury'),
  ('Marine Serre', 'luxury'),
  ('Simone Rocha', 'luxury'),
  ('Erdem', 'luxury'),
  ('Roksanda', 'luxury'),
  ('Victoria Beckham', 'luxury'),
  ('Mary Katrantzou', 'luxury'),
  ('Peter Pilotto', 'luxury'),
  ('Christopher Kane', 'luxury'),
  ('JW Anderson', 'luxury'),
  ('Loewe Paula''s Ibiza', 'luxury'),
  ('Fear of God', 'luxury'),
  ('Fear of God Essentials', 'luxury'),
  ('Amiri', 'luxury'),
  ('Rhude', 'luxury'),
  ('Kith', 'luxury'),
  ('Palm Angels', 'luxury'),
  ('Ambush', 'luxury'),
  ('Sacai', 'luxury'),
  ('Undercover', 'luxury'),
  ('Junya Watanabe', 'luxury'),
  ('Kenzo', 'luxury'),
  ('Paul Smith', 'luxury'),
  ('Vivienne Westwood', 'luxury'),
  ('Alexander Wang', 'luxury'),
  ('3.1 Phillip Lim', 'luxury'),
  ('Derek Lam', 'luxury'),
  ('Zimmermann', 'luxury'),
  ('Aje', 'luxury'),
  ('Camilla', 'luxury'),
  ('Johanna Ortiz', 'luxury'),
  ('Carolina Herrera', 'luxury'),
  ('Oscar de la Renta', 'luxury'),
  ('Michael Kors', 'luxury'),
  ('Kate Spade New York', 'luxury'),
  ('Tory Burch', 'luxury'),
  ('Diane von Furstenberg', 'luxury'),
  ('Vera Wang', 'luxury'),
  ('Marc Jacobs', 'luxury'),
  ('Coach', 'luxury'),
  ('Longchamp', 'luxury'),
  ('Mulberry', 'luxury'),
  ('Goyard', 'luxury'),
  ('Berluti', 'luxury'),
  ('Brioni', 'luxury'),
  ('Canali', 'luxury'),
  ('Kiton', 'luxury'),
  ('Corneliani', 'luxury'),
  ('Belstaff', 'luxury'),
  ('Barbour', 'luxury'),
  ('Aquascutum', 'luxury'),
  ('Mackintosh', 'luxury'),
  ('Dries Van Noten', 'luxury'),
  ('Ann Demeulemeester', 'luxury'),
  ('Raf Simons', 'luxury'),
  ('Haider Ackermann', 'luxury'),
  ('Y/Project', 'luxury'),
  ('Casablanca', 'luxury'),
  ('Wales Bonner', 'luxury'),
  ('Botter', 'luxury'),
  ('Kiko Kostadinov', 'luxury'),
  ('Sézane', 'contemporary'),
  ('Dôen', 'contemporary'),
  ('Reformation', 'contemporary'),
  ('Réalisation Par', 'contemporary'),
  ('Rouje', 'contemporary'),
  ('Ganni', 'contemporary'),
  ('Nanushka', 'contemporary'),
  ('Staud', 'contemporary'),
  ('Cult Gaia', 'contemporary'),
  ('Rejina Pyo', 'contemporary'),
  ('Rixo', 'contemporary'),
  ('Self-Portrait', 'contemporary'),
  ('Alice + Olivia', 'contemporary'),
  ('A.L.C.', 'contemporary'),
  ('Veronica Beard', 'contemporary'),
  ('Rag & Bone', 'contemporary'),
  ('Frame', 'contemporary'),
  ('Citizens of Humanity', 'contemporary'),
  ('Mother Denim', 'contemporary'),
  ('AGOLDE', 'contemporary'),
  ('Nili Lotan', 'contemporary'),
  ('Vince', 'contemporary'),
  ('Theory', 'contemporary'),
  ('Equipment', 'contemporary'),
  ('Joie', 'contemporary'),
  ('Rebecca Taylor', 'contemporary'),
  ('Ulla Johnson', 'contemporary'),
  ('Rachel Comey', 'contemporary'),
  ('Tibi', 'contemporary'),
  ('Rachel Antonoff', 'contemporary'),
  ('Apiece Apart', 'contemporary'),
  ('Cult of Individuality', 'contemporary'),
  ('Paige', 'contemporary'),
  ('DL1961', 'contemporary'),
  ('Hudson Jeans', 'contemporary'),
  ('Joe''s Jeans', 'contemporary'),
  ('7 For All Mankind', 'contemporary'),
  ('J Brand', 'contemporary'),
  ('Good American', 'contemporary'),
  ('Club Monaco', 'contemporary'),
  ('Banana Republic', 'contemporary'),
  ('J.Crew', 'contemporary'),
  ('Madewell', 'contemporary'),
  ('Everlane', 'contemporary'),
  ('COS', 'contemporary'),
  ('& Other Stories', 'contemporary'),
  ('Arket', 'contemporary'),
  ('Weekday', 'contemporary'),
  ('Monki', 'contemporary'),
  ('Uniqlo', 'contemporary'),
  ('Massimo Dutti', 'contemporary'),
  ('Mango', 'contemporary'),
  ('Zara', 'contemporary'),
  ('Bershka', 'contemporary'),
  ('Pull&Bear', 'contemporary'),
  ('Stradivarius', 'contemporary'),
  ('H&M', 'contemporary'),
  ('Gap', 'contemporary'),
  ('Old Navy', 'contemporary'),
  ('American Eagle', 'contemporary'),
  ('Abercrombie & Fitch', 'contemporary'),
  ('Hollister', 'contemporary'),
  ('Aerie', 'contemporary'),
  ('Anthropologie', 'contemporary'),
  ('Free People', 'contemporary'),
  ('Urban Outfitters', 'contemporary'),
  ('Aritzia', 'contemporary'),
  ('Wilfred', 'contemporary'),
  ('Babaton', 'contemporary'),
  ('Talula', 'contemporary'),
  ('Community by Aritzia', 'contemporary'),
  ('Nordstrom', 'contemporary'),
  ('Bloomingdale''s', 'contemporary'),
  ('Saks Fifth Avenue', 'contemporary'),
  ('Neiman Marcus', 'contemporary'),
  ('Revolve', 'contemporary'),
  ('Shopbop', 'contemporary'),
  ('Net-a-Porter', 'contemporary'),
  ('Farfetch', 'contemporary'),
  ('SSENSE', 'contemporary'),
  ('Matches Fashion', 'contemporary'),
  ('Mytheresa', 'contemporary'),
  ('Ba&sh', 'contemporary'),
  ('Sandro', 'contemporary'),
  ('Maje', 'contemporary'),
  ('Claudie Pierlot', 'contemporary'),
  ('The Kooples', 'contemporary'),
  ('Iro', 'contemporary'),
  ('American Vintage', 'contemporary'),
  ('Officine Générale', 'contemporary'),
  ('A.P.C.', 'contemporary'),
  ('Norse Projects', 'contemporary'),
  ('Our Legacy', 'contemporary'),
  ('Baum und Pferdgarten', 'contemporary'),
  ('Stine Goya', 'contemporary'),
  ('Cecilie Bahnsen', 'contemporary'),
  ('Rotate Birger Christensen', 'contemporary'),
  ('Saks Potts', 'contemporary'),
  ('Envelope1976', 'contemporary'),
  ('Skall Studio', 'contemporary'),
  ('Wood Wood', 'contemporary'),
  ('Han Kjøbenhavn', 'contemporary'),
  ('Filippa K', 'contemporary'),
  ('Whyred', 'contemporary'),
  ('Forever 21', 'fast_fashion'),
  ('Charlotte Russe', 'fast_fashion'),
  ('Rainbow Shops', 'fast_fashion'),
  ('Shein', 'fast_fashion'),
  ('Fashion Nova', 'fast_fashion'),
  ('PrettyLittleThing', 'fast_fashion'),
  ('Boohoo', 'fast_fashion'),
  ('Missguided', 'fast_fashion'),
  ('ASOS', 'fast_fashion'),
  ('Nasty Gal', 'fast_fashion'),
  ('Windsor', 'fast_fashion'),
  ('Cato Fashions', 'fast_fashion'),
  ('Ross Dress for Less', 'fast_fashion'),
  ('TJ Maxx', 'fast_fashion'),
  ('Marshalls', 'fast_fashion'),
  ('Burlington', 'fast_fashion'),
  ('Target', 'fast_fashion'),
  ('Walmart', 'fast_fashion'),
  ('Kmart', 'fast_fashion'),
  ('JCPenney', 'fast_fashion'),
  ('Sears', 'fast_fashion'),
  ('Kohl''s', 'fast_fashion'),
  ('Macy''s', 'fast_fashion'),
  ('Dillard''s', 'fast_fashion'),
  ('Belk', 'fast_fashion'),
  ('Stein Mart', 'fast_fashion'),
  ('Primark', 'fast_fashion'),
  ('New Look', 'fast_fashion'),
  ('River Island', 'fast_fashion'),
  ('Topshop', 'fast_fashion'),
  ('Topman', 'fast_fashion'),
  ('Miss Selfridge', 'fast_fashion'),
  ('Dorothy Perkins', 'fast_fashion'),
  ('Wallis', 'fast_fashion'),
  ('Debenhams', 'fast_fashion'),
  ('Peacocks', 'fast_fashion'),
  ('Matalan', 'fast_fashion'),
  ('George at Asda', 'fast_fashion'),
  ('F&F', 'fast_fashion'),
  ('Next', 'fast_fashion'),
  ('Marks & Spencer', 'fast_fashion'),
  ('John Lewis', 'fast_fashion'),
  ('C&A', 'fast_fashion'),
  ('Esprit', 'fast_fashion'),
  ('s.Oliver', 'fast_fashion'),
  ('Tom Tailor', 'fast_fashion'),
  ('Jack & Jones', 'fast_fashion'),
  ('Vero Moda', 'fast_fashion'),
  ('Only', 'fast_fashion'),
  ('Lefties', 'fast_fashion'),
  ('Suzy Shier', 'fast_fashion'),
  ('Ricki''s', 'fast_fashion'),
  ('Reitmans', 'fast_fashion'),
  ('Le Château', 'fast_fashion'),
  ('Winners', 'fast_fashion'),
  ('TK Maxx', 'fast_fashion'),
  ('Peek & Cloppenburg', 'fast_fashion'),
  ('Levi''s', 'denim'),
  ('Wrangler', 'denim'),
  ('Lee', 'denim'),
  ('Lucky Brand', 'denim'),
  ('True Religion', 'denim'),
  ('Diesel', 'denim'),
  ('Guess', 'denim'),
  ('Calvin Klein Jeans', 'denim'),
  ('Tommy Hilfiger Denim', 'denim'),
  ('Nudie Jeans', 'denim'),
  ('Naked & Famous', 'denim'),
  ('Raleigh Denim', 'denim'),
  ('3x1', 'denim'),
  ('RE/DONE', 'denim'),
  ('Denim & Supply', 'denim'),
  ('Silver Jeans Co.', 'denim'),
  ('Miss Me', 'denim'),
  ('Rock Revival', 'denim'),
  ('Big Star', 'denim'),
  ('Buffalo David Bitton', 'denim'),
  ('Kut from the Kloth', 'denim'),
  ('Blank NYC', 'denim'),
  ('Cheap Monday', 'denim'),
  ('Dr. Denim', 'denim'),
  ('Nobody Denim', 'denim'),
  ('Ksubi', 'denim'),
  ('One Teaspoon', 'denim'),
  ('Abrand Jeans', 'denim'),
  ('Neuw Denim', 'denim'),
  ('Edwin', 'denim'),
  ('Momotaro Jeans', 'denim'),
  ('Iron Heart', 'denim'),
  ('Full Count', 'denim'),
  ('Fear of God Denim', 'denim'),
  ('Warp + Weft', 'denim'),
  ('Nike', 'activewear'),
  ('Adidas', 'activewear'),
  ('Puma', 'activewear'),
  ('Under Armour', 'activewear'),
  ('Lululemon', 'activewear'),
  ('Athleta', 'activewear'),
  ('Alo Yoga', 'activewear'),
  ('Outdoor Voices', 'activewear'),
  ('Vuori', 'activewear'),
  ('Gymshark', 'activewear'),
  ('Fabletics', 'activewear'),
  ('Sweaty Betty', 'activewear'),
  ('Girlfriend Collective', 'activewear'),
  ('Beyond Yoga', 'activewear'),
  ('Splits59', 'activewear'),
  ('Varley', 'activewear'),
  ('Set Active', 'activewear'),
  ('Bandier', 'activewear'),
  ('P.E Nation', 'activewear'),
  ('Year of Ours', 'activewear'),
  ('Nimble Activewear', 'activewear'),
  ('Lorna Jane', 'activewear'),
  ('Tala', 'activewear'),
  ('Reebok', 'activewear'),
  ('New Balance', 'activewear'),
  ('Asics', 'activewear'),
  ('Champion', 'activewear'),
  ('Fila', 'activewear'),
  ('Kappa', 'activewear'),
  ('Ellesse', 'activewear'),
  ('Umbro', 'activewear'),
  ('Diadora', 'activewear'),
  ('Skechers', 'activewear'),
  ('Converse', 'activewear'),
  ('Vans', 'activewear'),
  ('Speedo', 'activewear'),
  ('TYR', 'activewear'),
  ('Arena', 'activewear'),
  ('Nike ACG', 'activewear'),
  ('Adidas Originals', 'activewear'),
  ('Adidas Terrex', 'activewear'),
  ('The North Face', 'activewear'),
  ('Columbia', 'activewear'),
  ('On Running', 'activewear'),
  ('Hoka', 'activewear'),
  ('Brooks', 'activewear'),
  ('Saucony', 'activewear'),
  ('Mizuno', 'activewear'),
  ('Salomon', 'activewear'),
  ('Arc''teryx', 'activewear'),
  ('Patagonia', 'activewear'),
  ('Prana', 'activewear'),
  ('Icebreaker', 'activewear'),
  ('Smartwool', 'activewear'),
  ('Marmot', 'outdoor'),
  ('Mountain Hardwear', 'outdoor'),
  ('REI Co-op', 'outdoor'),
  ('L.L.Bean', 'outdoor'),
  ('Eddie Bauer', 'outdoor'),
  ('Carhartt', 'outdoor'),
  ('Filson', 'outdoor'),
  ('Fjällräven', 'outdoor'),
  ('Helly Hansen', 'outdoor'),
  ('Canada Goose', 'outdoor'),
  ('Moncler Grenoble', 'outdoor'),
  ('Woolrich', 'outdoor'),
  ('Timberland', 'outdoor'),
  ('Merrell', 'outdoor'),
  ('Keen', 'outdoor'),
  ('Vasque', 'outdoor'),
  ('La Sportiva', 'outdoor'),
  ('Black Diamond', 'outdoor'),
  ('Cotopaxi', 'outdoor'),
  ('Outdoor Research', 'outdoor'),
  ('Rab', 'outdoor'),
  ('Berghaus', 'outdoor'),
  ('Craghoppers', 'outdoor'),
  ('Regatta', 'outdoor'),
  ('North Sails', 'outdoor'),
  ('Musto', 'outdoor'),
  ('Duluth Trading Co.', 'outdoor'),
  ('Dickies', 'outdoor'),
  ('Ben Davis', 'outdoor'),
  ('Red Wing', 'outdoor'),
  ('Danner', 'outdoor'),
  ('Dr. Martens', 'footwear'),
  ('Clarks', 'footwear'),
  ('Ecco', 'footwear'),
  ('Birkenstock', 'footwear'),
  ('UGG', 'footwear'),
  ('Crocs', 'footwear'),
  ('Toms', 'footwear'),
  ('Rothy''s', 'footwear'),
  ('Allbirds', 'footwear'),
  ('Cole Haan', 'footwear'),
  ('Steve Madden', 'footwear'),
  ('Sam Edelman', 'footwear'),
  ('Nine West', 'footwear'),
  ('Aldo', 'footwear'),
  ('Stuart Weitzman', 'footwear'),
  ('Gianvito Rossi', 'footwear'),
  ('Aquazzura', 'footwear'),
  ('Sophia Webster', 'footwear'),
  ('Frye', 'footwear'),
  ('Naturalizer', 'footwear'),
  ('Franco Sarto', 'footwear'),
  ('Kenneth Cole', 'footwear'),
  ('Bandolino', 'footwear'),
  ('Clarks Originals', 'footwear'),
  ('Hush Puppies', 'footwear'),
  ('Rockport', 'footwear'),
  ('Sperry', 'footwear'),
  ('Sebago', 'footwear'),
  ('Bass', 'footwear'),
  ('Tretorn', 'footwear'),
  ('Keds', 'footwear'),
  ('PF Flyers', 'footwear'),
  ('Superga', 'footwear'),
  ('Havaianas', 'footwear'),
  ('Reef', 'footwear'),
  ('Teva', 'footwear'),
  ('Chaco', 'footwear'),
  ('On Cloud', 'footwear'),
  ('Onitsuka Tiger', 'footwear'),
  ('Y-3', 'footwear'),
  ('Common Projects', 'footwear'),
  ('Veja', 'footwear'),
  ('Golden Goose', 'footwear'),
  ('Axel Arigato', 'footwear'),
  ('Koio', 'footwear'),
  ('Greats', 'footwear'),
  ('M.Gemi', 'footwear'),
  ('Margaux', 'footwear'),
  ('Loeffler Randall', 'footwear'),
  ('Supreme', 'streetwear'),
  ('Bape', 'streetwear'),
  ('Stussy', 'streetwear'),
  ('Palace', 'streetwear'),
  ('Chrome Hearts', 'streetwear'),
  ('Anti Social Social Club', 'streetwear'),
  ('The Hundreds', 'streetwear'),
  ('Obey', 'streetwear'),
  ('HUF', 'streetwear'),
  ('Diamond Supply Co.', 'streetwear'),
  ('Undefeated', 'streetwear'),
  ('10 Deep', 'streetwear'),
  ('Billionaire Boys Club', 'streetwear'),
  ('Ice Cream', 'streetwear'),
  ('Pleasures', 'streetwear'),
  ('Brain Dead', 'streetwear'),
  ('Aime Leon Dore', 'streetwear'),
  ('Noah', 'streetwear'),
  ('Carrots', 'streetwear'),
  ('Vlone', 'streetwear'),
  ('Trapstar', 'streetwear'),
  ('Corteiz', 'streetwear'),
  ('Cactus Plant Flea Market', 'streetwear'),
  ('Denim Tears', 'streetwear'),
  ('Sp5der', 'streetwear'),
  ('Golf Wang', 'streetwear'),
  ('Wtaps', 'streetwear'),
  ('Neighborhood', 'streetwear'),
  ('Visvim', 'streetwear'),
  ('Human Made', 'streetwear'),
  ('Cav Empt', 'streetwear'),
  ('Champion Reverse Weave', 'streetwear'),
  ('Carhartt WIP', 'streetwear'),
  ('Stone Island', 'streetwear'),
  ('CP Company', 'streetwear'),
  ('Maharishi', 'streetwear'),
  ('Represent', 'streetwear'),
  ('Daily Paper', 'streetwear'),
  ('Furla', 'accessories'),
  ('Fossil', 'accessories'),
  ('Rebecca Minkoff', 'accessories'),
  ('Mansur Gavriel', 'accessories'),
  ('Cuyana', 'accessories'),
  ('Senreve', 'accessories'),
  ('Strathberry', 'accessories'),
  ('Polène', 'accessories'),
  ('Wandler', 'accessories'),
  ('Anya Hindmarch', 'accessories'),
  ('Telfar', 'accessories'),
  ('Pinko', 'accessories'),
  ('Liu Jo', 'accessories'),
  ('Twinset', 'accessories'),
  ('Patrizia Pepe', 'accessories'),
  ('Kipling', 'accessories'),
  ('Herschel Supply Co.', 'accessories'),
  ('Fjällräven Kånken', 'accessories'),
  ('Baggu', 'accessories'),
  ('Away', 'accessories'),
  ('Béis', 'accessories'),
  ('Monos', 'accessories'),
  ('Rimowa', 'accessories'),
  ('Samsonite', 'accessories'),
  ('Tumi', 'accessories'),
  ('Briggs & Riley', 'accessories'),
  ('Bellroy', 'accessories'),
  ('Ray-Ban', 'accessories'),
  ('Oakley', 'accessories'),
  ('Persol', 'accessories'),
  ('Warby Parker', 'accessories'),
  ('Quay Australia', 'accessories'),
  ('Le Specs', 'accessories'),
  ('Gentle Monster', 'accessories'),
  ('Mejuri', 'accessories'),
  ('Pandora', 'accessories'),
  ('Swarovski', 'accessories'),
  ('Kendra Scott', 'accessories'),
  ('Ana Luisa', 'accessories'),
  ('Missoma', 'accessories'),
  ('Monica Vinader', 'accessories'),
  ('Catbird', 'accessories'),
  ('Aurate', 'accessories'),
  ('David Yurman', 'accessories'),
  ('Tiffany & Co.', 'accessories'),
  ('Cartier', 'accessories'),
  ('Van Cleef & Arpels', 'accessories'),
  ('Bulgari', 'accessories'),
  ('Polo Ralph Lauren', 'heritage_american'),
  ('Lauren Ralph Lauren', 'heritage_american'),
  ('Tommy Hilfiger', 'heritage_american'),
  ('Nautica', 'heritage_american'),
  ('Calvin Klein', 'heritage_american'),
  ('Brooks Brothers', 'heritage_american'),
  ('Land''s End', 'heritage_american'),
  ('Pendleton', 'heritage_american'),
  ('Wolverine', 'heritage_american'),
  ('Chippewa', 'heritage_american'),
  ('Schott NYC', 'heritage_american'),
  ('Alpha Industries', 'heritage_american'),
  ('Members Only', 'heritage_american'),
  ('Levi''s Vintage Clothing', 'heritage_american'),
  ('Woolrich Woolen Mills', 'heritage_american'),
  ('Gitman Bros.', 'heritage_american'),
  ('Todd Snyder', 'heritage_american'),
  ('J.Press', 'heritage_american'),
  ('Chipp', 'heritage_american'),
  ('O''Connell''s', 'heritage_american'),
  ('Kiel James Patrick', 'heritage_american'),
  ('Vineyard Vines', 'heritage_american'),
  ('Southern Tide', 'heritage_american'),
  ('Peter Millar', 'heritage_american'),
  ('Faherty', 'heritage_american'),
  ('Buck Mason', 'heritage_american'),
  ('Alex Mill', 'heritage_american'),
  ('Save Khaki United', 'heritage_american'),
  ('Corridor NYC', 'heritage_american'),
  ('Drake''s', 'heritage_american'),
  ('Suitsupply', 'menswear'),
  ('Bonobos', 'menswear'),
  ('Indochino', 'menswear'),
  ('Charles Tyrwhitt', 'menswear'),
  ('Ledbury', 'menswear'),
  ('Rhone', 'menswear'),
  ('Public Rec', 'menswear'),
  ('Mizzen+Main', 'menswear'),
  ('Ted Baker', 'menswear'),
  ('Hugo Boss', 'menswear'),
  ('Zegna', 'menswear'),
  ('Isaia', 'menswear'),
  ('Anderson & Sheppard', 'menswear'),
  ('Huntsman', 'menswear'),
  ('Gieves & Hawkes', 'menswear'),
  ('Turnbull & Asser', 'menswear'),
  ('Thomas Pink', 'menswear'),
  ('Eton Shirts', 'menswear'),
  ('Stenströms', 'menswear'),
  ('Reiss', 'menswear'),
  ('AllSaints', 'menswear'),
  ('Superdry', 'menswear'),
  ('Barbour International', 'menswear'),
  ('Fred Perry', 'menswear'),
  ('Lyle & Scott', 'menswear'),
  ('Pringle of Scotland', 'menswear'),
  ('Ben Sherman', 'menswear'),
  ('Jack Wills', 'menswear'),
  ('Selected Homme', 'menswear'),
  ('Carter''s', 'kids_maternity'),
  ('OshKosh B''gosh', 'kids_maternity'),
  ('Gap Kids', 'kids_maternity'),
  ('Gymboree', 'kids_maternity'),
  ('Janie and Jack', 'kids_maternity'),
  ('Hanna Andersson', 'kids_maternity'),
  ('Mini Boden', 'kids_maternity'),
  ('The Children''s Place', 'kids_maternity'),
  ('Crazy 8', 'kids_maternity'),
  ('Primary', 'kids_maternity'),
  ('Tea Collection', 'kids_maternity'),
  ('Rylee + Cru', 'kids_maternity'),
  ('Mori', 'kids_maternity'),
  ('Kyte Baby', 'kids_maternity'),
  ('Burt''s Bees Baby', 'kids_maternity'),
  ('Petit Bateau', 'kids_maternity'),
  ('Bonpoint', 'kids_maternity'),
  ('Il Gufo', 'kids_maternity'),
  ('Stella McCartney Kids', 'kids_maternity'),
  ('Molo', 'kids_maternity'),
  ('Mini Rodini', 'kids_maternity'),
  ('Wheat Kids', 'kids_maternity'),
  ('Seed Heritage', 'kids_maternity'),
  ('Country Road Kids', 'kids_maternity'),
  ('Motherhood Maternity', 'kids_maternity'),
  ('A Pea in the Pod', 'kids_maternity'),
  ('Seraphine', 'kids_maternity'),
  ('Hatch Collection', 'kids_maternity'),
  ('PinkBlush', 'kids_maternity'),
  ('Ingrid & Isabel', 'kids_maternity'),
  ('Vera Wang Bride', 'bridal_formal'),
  ('BHLDN', 'bridal_formal'),
  ('David''s Bridal', 'bridal_formal'),
  ('Watters', 'bridal_formal'),
  ('Jenny Yoo', 'bridal_formal'),
  ('Monique Lhuillier', 'bridal_formal'),
  ('Galia Lahav', 'bridal_formal'),
  ('Berta', 'bridal_formal'),
  ('Pronovias', 'bridal_formal'),
  ('Rosa Clará', 'bridal_formal'),
  ('Justin Alexander', 'bridal_formal'),
  ('Maggie Sottero', 'bridal_formal'),
  ('Allure Bridals', 'bridal_formal'),
  ('Essense of Australia', 'bridal_formal'),
  ('Stella York', 'bridal_formal'),
  ('Rebecca Ingram', 'bridal_formal'),
  ('Azazie', 'bridal_formal'),
  ('Faviana', 'bridal_formal'),
  ('Sherri Hill', 'bridal_formal'),
  ('Jovani', 'bridal_formal'),
  ('Badgley Mischka', 'bridal_formal'),
  ('Marchesa', 'bridal_formal'),
  ('Zac Posen', 'bridal_formal'),
  ('Reem Acra', 'bridal_formal'),
  ('Vitamin A', 'swimwear'),
  ('Solid & Striped', 'swimwear'),
  ('Mara Hoffman Swim', 'swimwear'),
  ('Onia', 'swimwear'),
  ('Frankies Bikinis', 'swimwear'),
  ('L*Space', 'swimwear'),
  ('Tori Praver Swimwear', 'swimwear'),
  ('Eres', 'swimwear'),
  ('La Perla', 'swimwear'),
  ('Melissa Odabash', 'swimwear'),
  ('Heidi Klein', 'swimwear'),
  ('Seafolly', 'swimwear'),
  ('Jets Swimwear', 'swimwear'),
  ('Tigerlily', 'swimwear'),
  ('Roxy', 'swimwear'),
  ('Billabong', 'swimwear'),
  ('Quiksilver', 'swimwear'),
  ('Rip Curl', 'swimwear'),
  ('O''Neill', 'swimwear'),
  ('Hurley', 'swimwear'),
  ('Volcom', 'swimwear'),
  ('Cupshe', 'swimwear'),
  ('Andie Swim', 'swimwear'),
  ('Summersalt', 'swimwear'),
  ('Eberjey', 'sleepwear'),
  ('Skims', 'sleepwear'),
  ('Cosabella', 'sleepwear'),
  ('Hanky Panky', 'sleepwear'),
  ('Natori', 'sleepwear'),
  ('Journelle', 'sleepwear'),
  ('Araks', 'sleepwear'),
  ('Sleeper', 'sleepwear'),
  ('Lunya', 'sleepwear'),
  ('Petite Plume', 'sleepwear'),
  ('Olivia von Halle', 'sleepwear'),
  ('Morgan Lane', 'sleepwear'),
  ('Papinelle', 'sleepwear'),
  ('Victoria''s Secret', 'sleepwear'),
  ('Soma', 'sleepwear'),
  ('Wacoal', 'sleepwear'),
  ('Spanx', 'sleepwear'),
  ('Third Love', 'sleepwear'),
  ('True & Co.', 'sleepwear'),
  ('Adore Me', 'sleepwear'),
  ('Savage X Fenty', 'sleepwear'),
  ('Torrid', 'plus_size'),
  ('Lane Bryant', 'plus_size'),
  ('Eloquii', 'plus_size'),
  ('Universal Standard', 'plus_size'),
  ('Good American Curve', 'plus_size'),
  ('City Chic', 'plus_size'),
  ('Ashley Stewart', 'plus_size'),
  ('Fashion to Figure', 'plus_size'),
  ('Catherines', 'plus_size'),
  ('Woman Within', 'plus_size'),
  ('Roaman''s', 'plus_size'),
  ('Avenue', 'plus_size'),
  ('11 Honoré', 'plus_size'),
  ('Chromat', 'plus_size'),
  ('Christian Siriano Curve', 'plus_size'),
  ('Pact', 'sustainable_dtc'),
  ('Eileen Fisher', 'sustainable_dtc'),
  ('Amour Vert', 'sustainable_dtc'),
  ('Kotn', 'sustainable_dtc'),
  ('Quince', 'sustainable_dtc'),
  ('People Tree', 'sustainable_dtc'),
  ('Thought Clothing', 'sustainable_dtc'),
  ('Armedangels', 'sustainable_dtc'),
  ('Outerknown', 'sustainable_dtc'),
  ('Christy Dawn', 'sustainable_dtc'),
  ('Elizabeth Suzann', 'sustainable_dtc'),
  ('Colorful Standard', 'sustainable_dtc'),
  ('Organic Basics', 'sustainable_dtc'),
  ('Baukjen', 'sustainable_dtc'),
  ('Wolven', 'sustainable_dtc'),
  ('Muji', 'global_regional'),
  ('GU', 'global_regional'),
  ('Beams', 'global_regional'),
  ('United Arrows', 'global_regional'),
  ('Descente', 'global_regional'),
  ('Snow Peak', 'global_regional'),
  ('Goldwin', 'global_regional'),
  ('Ader Error', 'global_regional'),
  ('Andersson Bell', 'global_regional'),
  ('Wooyoungmi', 'global_regional'),
  ('Juun.J', 'global_regional'),
  ('Blindness', 'global_regional'),
  ('Thisisneverthat', 'global_regional'),
  ('Marithé François Girbaud', 'global_regional'),
  ('Country Road', 'global_regional'),
  ('Witchery', 'global_regional'),
  ('Cue', 'global_regional'),
  ('Sportsgirl', 'global_regional'),
  ('Cotton On', 'global_regional'),
  ('Bassike', 'global_regional'),
  ('Ginger & Smart', 'global_regional'),
  ('Scanlan Theodore', 'global_regional'),
  ('sass & bide', 'global_regional'),
  ('Kookaï', 'global_regional'),
  ('Sportscraft', 'global_regional'),
  ('David Lawrence', 'global_regional'),
  ('Karen Millen', 'global_regional'),
  ('Coast', 'global_regional'),
  ('Phase Eight', 'global_regional'),
  ('Whistles', 'global_regional'),
  ('L.K.Bennett', 'global_regional'),
  ('Hobbs London', 'global_regional'),
  ('Jigsaw', 'global_regional'),
  ('French Connection', 'global_regional'),
  ('Warehouse', 'global_regional'),
  ('Oasis', 'global_regional'),
  ('Monsoon', 'global_regional'),
  ('Jaeger', 'global_regional'),
  ('Tiger of Sweden', 'global_regional'),
  ('Gant', 'global_regional'),
  ('J.Lindeberg', 'global_regional'),
  ('Odd Molly', 'global_regional'),
  ('Rodebjer', 'global_regional'),
  ('Won Hundred', 'global_regional'),
  ('Samsøe Samsøe', 'global_regional'),
  ('By Malene Birger', 'global_regional'),
  ('Munthe', 'global_regional'),
  ('Day Birger et Mikkelsen', 'global_regional'),
  ('Loft', 'department_specialty'),
  ('Ann Taylor', 'department_specialty'),
  ('White House Black Market', 'department_specialty'),
  ('Chico''s', 'department_specialty'),
  ('Talbots', 'department_specialty'),
  ('J.Jill', 'department_specialty'),
  ('Dress Barn', 'department_specialty'),
  ('New York & Company', 'department_specialty'),
  ('Express', 'department_specialty'),
  ('bebe', 'department_specialty'),
  ('Rampage', 'department_specialty'),
  ('Cache', 'department_specialty'),
  ('Wet Seal', 'department_specialty'),
  ('Zumiez', 'department_specialty'),
  ('PacSun', 'department_specialty'),
  ('Tilly''s', 'department_specialty'),
  ('Hot Topic', 'department_specialty'),
  ('Journeys', 'department_specialty'),
  ('Foot Locker', 'department_specialty'),
  ('Halston', 'vintage_designer'),
  ('Bill Blass', 'vintage_designer'),
  ('Anne Klein', 'vintage_designer'),
  ('Liz Claiborne', 'vintage_designer'),
  ('Perry Ellis', 'vintage_designer'),
  ('Calvin Klein Vintage', 'vintage_designer'),
  ('Geoffrey Beene', 'vintage_designer'),
  ('Adolfo', 'vintage_designer'),
  ('Givenchy Vintage', 'vintage_designer'),
  ('Yves Saint Laurent Rive Gauche', 'vintage_designer'),
  ('Emanuel Ungaro', 'vintage_designer'),
  ('Guy Laroche', 'vintage_designer'),
  ('Pierre Cardin', 'vintage_designer'),
  ('Christian Dior Vintage', 'vintage_designer'),
  ('Courrèges', 'vintage_designer'),
  ('Paco Rabanne', 'vintage_designer'),
  ('Missoni', 'vintage_designer'),
  ('Emilio Pucci', 'vintage_designer'),
  ('Gianni Versace Vintage', 'vintage_designer'),
  ('Moschino', 'vintage_designer'),
  ('Fiorucci', 'vintage_designer'),
  ('Escada', 'vintage_designer'),
  ('Gianfranco Ferré', 'vintage_designer'),
  ('Krizia', 'vintage_designer'),
  ('Byblos', 'vintage_designer'),
  ('Guess Vintage', 'vintage_designer'),
  ('Esprit Vintage', 'vintage_designer'),
  ('Benetton', 'vintage_designer'),
  ('United Colors of Benetton', 'vintage_designer'),
  ('Sisley', 'vintage_designer'),
  ('Diesel Vintage', 'vintage_designer'),
  ('Iceberg', 'vintage_designer'),
  ('Cerruti 1881', 'vintage_designer'),
  ('Trussardi', 'vintage_designer'),
  ('Gucci Vintage', 'vintage_designer'),
  ('Fendi Vintage', 'vintage_designer'),
  ('Bonnie Cashin', 'vintage_designer'),
  ('Rudi Gernreich', 'vintage_designer'),
  ('Norma Kamali', 'vintage_designer'),
  ('Betsey Johnson', 'vintage_designer'),
  ('Anna Sui', 'vintage_designer'),
  ('Cynthia Rowley', 'vintage_designer'),
  ('Nicole Miller', 'vintage_designer'),
  ('Diane von Furstenberg Vintage', 'vintage_designer'),
  ('Halston Heritage', 'vintage_designer'),
  ('FootJoy', 'golf_tennis'),
  ('Titleist', 'golf_tennis'),
  ('Nike Golf', 'golf_tennis'),
  ('Adidas Golf', 'golf_tennis'),
  ('Under Armour Golf', 'golf_tennis'),
  ('Ashworth', 'golf_tennis'),
  ('Peter Millar Golf', 'golf_tennis'),
  ('Callaway Apparel', 'golf_tennis'),
  ('TravisMathew', 'golf_tennis'),
  ('Puma Golf', 'golf_tennis'),
  ('G/FORE', 'golf_tennis'),
  ('Malbon Golf', 'golf_tennis'),
  ('Lululemon Golf', 'golf_tennis'),
  ('J.Lindeberg Golf', 'golf_tennis'),
  ('Fila Tennis', 'golf_tennis'),
  ('Wilson Apparel', 'golf_tennis'),
  ('Ellesse Tennis', 'golf_tennis'),
  ('Lacoste', 'golf_tennis'),
  ('Sergio Tacchini', 'golf_tennis'),
  ('Australian Sportswear', 'golf_tennis'),
  ('Head Apparel', 'golf_tennis'),
  ('Babolat Apparel', 'golf_tennis'),
  ('Fred Perry Tennis', 'golf_tennis'),
  ('Tory Sport', 'golf_tennis'),
  ('Red Kap', 'workwear_uniform'),
  ('Cintas', 'workwear_uniform'),
  ('Dickies Workwear', 'workwear_uniform'),
  ('Carhartt Workwear', 'workwear_uniform'),
  ('Carhartt WIP Workwear', 'workwear_uniform'),
  ('Timberland PRO', 'workwear_uniform'),
  ('Wolverine Workwear', 'workwear_uniform'),
  ('Figs', 'workwear_uniform'),
  ('Jaanuu', 'workwear_uniform'),
  ('Cherokee Uniforms', 'workwear_uniform'),
  ('Landau', 'workwear_uniform'),
  ('Barco Uniforms', 'workwear_uniform'),
  ('Grey''s Anatomy Scrubs', 'workwear_uniform'),
  ('Dickies Medical', 'workwear_uniform'),
  ('WonderWink', 'workwear_uniform'),
  ('Koi Scrubs', 'workwear_uniform'),
  ('Ariat Workwear', 'workwear_uniform'),
  ('Wrangler Workwear', 'workwear_uniform'),
  ('Ben Davis Workwear', 'workwear_uniform'),
  ('Round House', 'workwear_uniform'),
  ('Key Apparel', 'workwear_uniform'),
  ('Berne Apparel', 'workwear_uniform'),
  ('Carharrt Detroit', 'workwear_uniform'),
  ('Quiksilver Skate', 'surf_skate'),
  ('Volcom Skate', 'surf_skate'),
  ('Vans Skate', 'surf_skate'),
  ('Element Skateboards', 'surf_skate'),
  ('DC Shoes', 'surf_skate'),
  ('Etnies', 'surf_skate'),
  ('Emerica', 'surf_skate'),
  ('Globe', 'surf_skate'),
  ('éS Skateboarding', 'surf_skate'),
  ('Zero Skateboards', 'surf_skate'),
  ('Girl Skateboards', 'surf_skate'),
  ('Santa Cruz Skateboards', 'surf_skate'),
  ('Thrasher', 'surf_skate'),
  ('RVCA', 'surf_skate'),
  ('Insight', 'surf_skate'),
  ('Ambiguous Clothing', 'surf_skate'),
  ('Lost Enterprises', 'surf_skate'),
  ('Reef Surf', 'surf_skate'),
  ('Billabong Surf', 'surf_skate'),
  ('Rip Curl Surf', 'surf_skate'),
  ('Hurley Surf', 'surf_skate'),
  ('O''Neill Surf', 'surf_skate'),
  ('Body Glove', 'surf_skate'),
  ('Farm Rio', 'latin_america'),
  ('Osklen', 'latin_america'),
  ('Água de Coco', 'latin_america'),
  ('Cia. Marítima', 'latin_america'),
  ('Rosa Chá', 'latin_america'),
  ('Colcci', 'latin_america'),
  ('AREZZO', 'latin_america'),
  ('Schutz', 'latin_america'),
  ('Melissa', 'latin_america'),
  ('Havaianas Brasil', 'latin_america'),
  ('Reserva', 'latin_america'),
  ('Animale', 'latin_america'),
  ('Le Lis Blanc', 'latin_america'),
  ('Cantão', 'latin_america'),
  ('Blue Man Brasil', 'latin_america'),
  ('FabIndia', 'middle_east_india'),
  ('Anita Dongre', 'middle_east_india'),
  ('Sabyasachi', 'middle_east_india'),
  ('Manish Malhotra', 'middle_east_india'),
  ('Global Desi', 'middle_east_india'),
  ('W for Woman', 'middle_east_india'),
  ('Biba', 'middle_east_india'),
  ('AND Designs', 'middle_east_india'),
  ('Van Heusen India', 'middle_east_india'),
  ('Allen Solly', 'middle_east_india'),
  ('Peter England', 'middle_east_india'),
  ('Raymond', 'middle_east_india'),
  ('Levi''s India', 'middle_east_india'),
  ('Norse Store', 'scandinavian'),
  ('Elvine', 'scandinavian'),
  ('Makia Clothing', 'scandinavian'),
  ('Halo Sportswear', 'scandinavian'),
  ('Peak Performance', 'scandinavian'),
  ('Bergans', 'scandinavian'),
  ('Didriksons', 'scandinavian'),
  ('Klättermusen', 'scandinavian'),
  ('Houdini Sportswear', 'scandinavian'),
  ('Kavat', 'scandinavian'),
  ('Ilse Jacobsen', 'scandinavian'),
  ('Won Hundred Copenhagen', 'scandinavian'),
  ('Résumé', 'scandinavian'),
  ('Custommade', 'scandinavian'),
  ('Mads Nørgaard', 'scandinavian'),
  ('8Seconds', 'korean_chinese'),
  ('SPAO', 'korean_chinese'),
  ('Musinsa', 'korean_chinese'),
  ('Charm''s Korea', 'korean_chinese'),
  ('Codibook', 'korean_chinese'),
  ('Aland', 'korean_chinese'),
  ('Stylenanda', 'korean_chinese'),
  ('Chuu', 'korean_chinese'),
  ('Ordinary People', 'korean_chinese'),
  ('Cover Nat', 'korean_chinese'),
  ('Napa by Martine Rose', 'korean_chinese'),
  ('Li-Ning', 'korean_chinese'),
  ('Anta', 'korean_chinese'),
  ('Peacebird', 'korean_chinese'),
  ('Metersbonwe', 'korean_chinese'),
  ('Urban Revivo', 'korean_chinese'),
  ('Bosideng', 'korean_chinese'),
  ('Erdos Cashmere', 'korean_chinese'),
  ('Icicle', 'korean_chinese'),
  ('Princess Polly', 'gen_z_dtc'),
  ('Motel Rocks', 'gen_z_dtc'),
  ('Meshki', 'gen_z_dtc'),
  ('Oh Polly', 'gen_z_dtc'),
  ('White Fox Boutique', 'gen_z_dtc'),
  ('Beginning Boutique', 'gen_z_dtc'),
  ('Selfie Leslie', 'gen_z_dtc'),
  ('Edikted', 'gen_z_dtc'),
  ('House of CB', 'gen_z_dtc'),
  ('Petal & Pup', 'gen_z_dtc'),
  ('Verge Girl', 'gen_z_dtc'),
  ('Lioness', 'gen_z_dtc'),
  ('Bec + Bridge', 'gen_z_dtc'),
  ('Alice McCall', 'gen_z_dtc'),
  ('Kookai Australia', 'gen_z_dtc'),
  ('Runaway The Label', 'gen_z_dtc'),
  ('Third Form', 'gen_z_dtc'),
  ('Spanx Shapewear', 'hosiery_shapewear'),
  ('Skims Shapewear', 'hosiery_shapewear'),
  ('Yummie', 'hosiery_shapewear'),
  ('Commando', 'hosiery_shapewear'),
  ('Wolford', 'hosiery_shapewear'),
  ('Hue Legwear', 'hosiery_shapewear'),
  ('Falke', 'hosiery_shapewear'),
  ('Calzedonia', 'hosiery_shapewear'),
  ('Bloch', 'hosiery_shapewear'),
  ('Sigvaris', 'hosiery_shapewear'),
  ('Assets by Spanx', 'hosiery_shapewear'),
  ('Maidenform', 'hosiery_shapewear'),
  ('Bali', 'hosiery_shapewear'),
  ('Playtex', 'hosiery_shapewear'),
  ('Vanity Fair Lingerie', 'hosiery_shapewear'),
  ('Warner''s', 'hosiery_shapewear'),
  ('New Era', 'hats_headwear'),
  ('Mitchell & Ness', 'hats_headwear'),
  ('''47 Brand', 'hats_headwear'),
  ('Goorin Bros.', 'hats_headwear'),
  ('Brixton', 'hats_headwear'),
  ('Kangol', 'hats_headwear'),
  ('Stetson', 'hats_headwear'),
  ('Borsalino', 'hats_headwear'),
  ('Panama Jack', 'hats_headwear'),
  ('San Diego Hat Co.', 'hats_headwear'),
  ('lululemon Headwear', 'hats_headwear'),
  ('Herschel Headwear', 'hats_headwear'),
  ('Patagonia Hats', 'hats_headwear'),
  ('Carhartt Beanies', 'hats_headwear'),
  ('Toms Shoes Co.', 'footwear_extra'),
  ('Journee Collection', 'footwear_extra'),
  ('Dolce Vita', 'footwear_extra'),
  ('Jeffrey Campbell', 'footwear_extra'),
  ('Free People Shoes', 'footwear_extra'),
  ('Circus by Sam Edelman', 'footwear_extra'),
  ('Marc Fisher', 'footwear_extra'),
  ('Vince Camuto', 'footwear_extra'),
  ('Report Footwear', 'footwear_extra'),
  ('Chinese Laundry', 'footwear_extra'),
  ('Matisse Footwear', 'footwear_extra'),
  ('Seychelles Footwear', 'footwear_extra'),
  ('Coconuts by Matisse', 'footwear_extra'),
  ('Sorel', 'footwear_extra'),
  ('Blundstone', 'footwear_extra'),
  ('R.M.Williams', 'footwear_extra'),
  ('Ariat Boots', 'footwear_extra'),
  ('Justin Boots', 'footwear_extra'),
  ('Tony Lama', 'footwear_extra'),
  ('Lucchese', 'footwear_extra'),
  ('Frye Boot Co.', 'footwear_extra'),
  ('Palladium Boots', 'footwear_extra'),
  ('Native Shoes', 'footwear_extra'),
  ('Gabriela Hearst', 'luxury_extra'),
  ('Altuzarra', 'luxury_extra'),
  ('Brandon Maxwell', 'luxury_extra'),
  ('Prabal Gurung', 'luxury_extra'),
  ('Jonathan Simkhai', 'luxury_extra'),
  ('Cushnie', 'luxury_extra'),
  ('Monse', 'luxury_extra'),
  ('Rosie Assoulin', 'luxury_extra'),
  ('Sies Marjan', 'luxury_extra'),
  ('Area', 'luxury_extra'),
  ('Batsheva', 'luxury_extra'),
  ('LoveShackFancy', 'luxury_extra'),
  ('Doen Studio', 'luxury_extra'),
  ('Hellessy', 'luxury_extra'),
  ('Markarian', 'luxury_extra'),
  ('Rachel Gilbert', 'luxury_extra'),
  ('Alex Perry', 'luxury_extra'),
  ('Aliette Studio', 'luxury_extra'),
  ('Rejina Pyo London', 'luxury_extra'),
  ('Nensi Dojaka', 'luxury_extra')
on conflict (name) do nothing;
